// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © JJPP_Joel
//@version=6

strategy("Golden Friday", overlay=true, fill_orders_on_standard_ohlc = true)

bool session = (dayofweek == dayofweek.friday) and (hour>= 14 and hour <= 16)

bool long_condition = false
bool short_condition = false

if session
    if hour <= 14
        long_condition := true
    if hour >= 16
        short_condition := true

if (long_condition)
    strategy.entry("My Long Entry Id", strategy.long)
 
if (short_condition)
    strategy.entry("My Short Entry Id", strategy.short)

color color_session   = input.color(defval = color.red,title="Color session",display = display.none) 
int transparency = input.int(defval = 80, title="Transparency (%)", minval=0, maxval=100)

// Colour the background of each session
bgcolor(color= session ? color.new(color_session, transparency) : na, title="New York")
