// This Pine Script® code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © JJPP_Joel
// Author: Joel Pasapera Pinto
//@version=6

// Constants
var int initial_balance = 10000 // set a realistic initial balance

strategy("Time and schedule", overlay=true, fill_orders_on_standard_ohlc = true, initial_capital = initial_balance, calc_on_every_tick = true)

// Inputs are defined
float lot_size = input.float(defval = 1, title = "lot_size",step=0.1)
int start_time = input.int(defval = 13, title="Start time", minval=0, maxval=24)
int end_time = input.int(defval = 16, title="End time", minval=0, maxval=24)
bool buy_or_sell = input.bool(defval = true, title = "Buy? (otherwise sell)")
int day_of_week = input.int(defval = dayofweek.friday, title = "dayofweek",minval=0,maxval=8)
color color_session   = input.color(defval = color.red,title="Color session",display = display.none) 
int transparency = input.int(defval = 80, title="Transparency (%)", minval=0, maxval=100)

// Global variables are defined
bool long_condition = false
bool short_condition = false

// The current bar is inside of the session?
bool in_session = (dayofweek == day_of_week) and (hour>= start_time and hour <= end_time)

// Buy and sell condition
if in_session
    if hour <= start_time
        long_condition := true // buy
        
    if hour >= end_time
        short_condition := true // sell

// Buy or sell with the signal?
if (buy_or_sell ? long_condition : short_condition) 
    strategy.entry("My Long Entry Id", strategy.long,qty = lot_size)
    
if (buy_or_sell ? short_condition : long_condition) 
    strategy.entry("My Short Entry Id", strategy.short, qty = lot_size)
    

// Colour the background of each in_session
bgcolor(color= in_session ? color.new(color_session, transparency) : na, title="New York")
